version: "3.9"
services:
  client:
    build:
      context: .
      dockerfile: ./cmd/client/Dockerfile
    image: asynq-poc-client:latest
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: ./cmd/worker/Dockerfile
    image: asynq-poc-worker:latest
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"

  asynqmon:
    image: hibiken/asynqmon:0.7.2
    command: "--redis-url=redis://redis:6379"
    ports:
      - "8080:8080"